# Use Ubuntu 14.04
dist: trusty

sudo: false

language: ruby

rvm: 2.2.3

cache:
  - apt
  - bundler
  - directories:
    - $HOME/.ivy2/cache

jdk:
  - openjdk7

install:
  - gem install nanoc:4.0.2
  - gem install redcarpet
  - gem install nokogiri

addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.bintray.com/sbt/debian /'
        key_url: 'https://bintray.com/user/downloadSubjectPublicKey?username=sbt'
    packages:
      - sbt
      - pandoc
      - latex-cjk-all
      - texlive-full

before_script:
 - export JVM_OPTS="-Dfile.encoding=UTF-8 -Xmx1G -Xms1G -server -XX:ReservedCodeCacheSize=128M -XX:MaxPermSize=512M"

script:
  - sbt makeSite
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
  - export SBT_GHPAGES_COMMIT_MESSAGE="updated site https://github.com/sbt/website/commit/${TRAVIS_COMMIT}"
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "1.x" && "${TRAVIS_REPO_SLUG}" == "sbt/website" ]]; then export PUBLISH_SITE=true; fi
  - test "${PUBLISH_SITE}" == "true" && eval "$(ssh-agent -s)" #start the ssh agent
  - test "${PUBLISH_SITE}" == "true" && openssl aes-256-cbc -K $encrypted_e29f8a2ff2bf_key -iv $encrypted_e29f8a2ff2bf_iv -in deploy_rsa.enc -out deploy_rsa -d
  - test "${PUBLISH_SITE}" == "true" && chmod 600 deploy_rsa
  - test "${PUBLISH_SITE}" == "true" && ssh-add deploy_rsa
  - test "${PUBLISH_SITE}" == "true" && sbt ghpagesPushSite

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete
