# Use Ubuntu 14.04
dist: trusty
sudo: false
language: ruby
rvm: 2.2.3
cache:
  - apt
  - bundler
  - directories:
    - $HOME/.ivy2/cache
script:
  - sbt makeSite
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
jdk:
  - openjdk7
install:
  - gem install nanoc:4.0.2
  - gem install redcarpet
  - gem install nokogiri
addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.bintray.com/sbt/debian /'
        key_url: 'https://bintray.com/user/downloadSubjectPublicKey?username=sbt'
    packages:
      - sbt
      - pandoc
      - latex-cjk-all
      - texlive-full
before_script:
 - export JVM_OPTS="-Dfile.encoding=UTF-8"
