language: ruby
rvm: 2.2.x
cache:
  apt: true
  directories:
    - $HOME/.ivy2/cache
script:
  - sbt makeSite
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
jdk:
  - oraclejdk7
notifications:
  email:
    - qbranch@typesafe.com
install:
  - gem install nanoc:4.0.0
  - gem install redcarpet
  - gem install nokogiri
before_install:
 - sudo add-apt-repository -y ppa:texlive-backports/ppa
 - sudo apt-get update -qq
 - sudo apt-get install -qq ruby-dev pandoc latex-cjk-all texlive-full
before_script:
  - export JVM_OPTS="-Xms1024m -Xmx1024m -XX:ReservedCodeCacheSize=128m -XX:MaxPermSize=256m -Xss1m"
