# Use Ubuntu 14.04
dist: trusty

sudo: false

language: ruby

rvm: 2.2.3

cache:
  - apt
  - bundler
  - directories:
    - $HOME/.ivy2/cache

jdk:
  - openjdk7

install:
  - gem install nanoc:4.0.2
  - gem install redcarpet
  - gem install nokogiri

addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.bintray.com/sbt/debian /'
        key_url: 'https://bintray.com/user/downloadSubjectPublicKey?username=sbt'
    packages:
      - sbt
      - pandoc
      - latex-cjk-all
      - texlive-full

before_script:
 - export JVM_OPTS="-Dfile.encoding=UTF-8 -Xmx1G -Xms1G -server -XX:ReservedCodeCacheSize=128M -XX:MaxPermSize=512M"

script:
  - sbt makeSite
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

env:
  secure: "V5m4XzcIFrhpSMlaXNSNJtciuv8aM9Ud2ww08R1Cxh6Juqag3aY5lTnIdfjR3GLk7frheOjdi8mi8ETKRRMEvS/4mw070LT9s4uQFiIG/myARfNZEGbX4YrFxBZEvdxlOgdgQ8gjeaD2N/b7l7ZZbX+d/2jPIeLSFLlmcFpjn0kil36C/tTA52o7LeziJH5rYfJIGGBn+06CgOK73L06f81ELav4YFJsQ7l6EbhCzF6cdJdyqDtITYaw6e4X9klE8C0i+PLP+26gdjCM3z57wrb9mhKETaZoCO/Z/QnR013A6NHycV/Tkn8B0PwMIJpG/GU4AFS2jCL20fM3rrPC5Pty/XPc6vvZGw5NDDYjRxm/a1Udj115m6HJfVsXwfFSfbnI4tgOISxpPB7FK/QzsmoJXpGlmppNkMwCelw1XRz6Oz87cdLC+5xeL0A417byYSczB/TrF6Tbj8VPzJkDtMAvcZFmFySAIn6M/RflxACe3NvCGat+ia4x4djiTo80EQiTgSM93V8MQ7KNGx1XVrqvkSWADer9CNHC/sieVAa5c0Rvo9RUjv+lVV9FH1Pt4Jx2wqMUKs7B3fPVfYAjlTKXpfI8XLtgDfSMtGk/kJDmn3GEYWFkZv6bsALSeZdnDQ54/mMEk0fCU8XWX/eeAXfiPQ8wqrsL/+Ww1uicCCQ="

after_success:
  - .travis/publish-site.sh

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete
